export interface EspnTeam {
  name: string;
  aliases?: string[];
  leagueLabel: string;
  sport: string;   // ESPN API path segment: football | basketball | baseball | hockey | soccer
  league: string;  // ESPN API path segment: nfl | nba | mlb | nhl | eng.1
  espnId: string;
}

export const ESPN_TEAMS: EspnTeam[] = [
  // ── NFL ────────────────────────────────────────────────────────────────────
  { name: "Arizona Cardinals",    leagueLabel: "NFL", sport: "football", league: "nfl", espnId: "22" },
  { name: "Atlanta Falcons",      leagueLabel: "NFL", sport: "football", league: "nfl", espnId: "1"  },
  { name: "Baltimore Ravens",     leagueLabel: "NFL", sport: "football", league: "nfl", espnId: "33" },
  { name: "Buffalo Bills",        leagueLabel: "NFL", sport: "football", league: "nfl", espnId: "2"  },
  { name: "Carolina Panthers",    leagueLabel: "NFL", sport: "football", league: "nfl", espnId: "29" },
  { name: "Chicago Bears",        leagueLabel: "NFL", sport: "football", league: "nfl", espnId: "3"  },
  { name: "Cincinnati Bengals",   leagueLabel: "NFL", sport: "football", league: "nfl", espnId: "4"  },
  { name: "Cleveland Browns",     leagueLabel: "NFL", sport: "football", league: "nfl", espnId: "5"  },
  { name: "Dallas Cowboys",       leagueLabel: "NFL", sport: "football", league: "nfl", espnId: "6"  },
  { name: "Denver Broncos",       leagueLabel: "NFL", sport: "football", league: "nfl", espnId: "7"  },
  { name: "Detroit Lions",        leagueLabel: "NFL", sport: "football", league: "nfl", espnId: "8"  },
  { name: "Green Bay Packers",    leagueLabel: "NFL", sport: "football", league: "nfl", espnId: "9"  },
  { name: "Houston Texans",       leagueLabel: "NFL", sport: "football", league: "nfl", espnId: "34" },
  { name: "Indianapolis Colts",   leagueLabel: "NFL", sport: "football", league: "nfl", espnId: "11" },
  { name: "Jacksonville Jaguars", leagueLabel: "NFL", sport: "football", league: "nfl", espnId: "30" },
  { name: "Kansas City Chiefs",   leagueLabel: "NFL", sport: "football", league: "nfl", espnId: "12" },
  { name: "Las Vegas Raiders",    leagueLabel: "NFL", sport: "football", league: "nfl", espnId: "13" },
  { name: "Los Angeles Chargers", leagueLabel: "NFL", sport: "football", league: "nfl", espnId: "24" },
  { name: "Los Angeles Rams",     leagueLabel: "NFL", sport: "football", league: "nfl", espnId: "14" },
  { name: "Miami Dolphins",       leagueLabel: "NFL", sport: "football", league: "nfl", espnId: "15" },
  { name: "Minnesota Vikings",    leagueLabel: "NFL", sport: "football", league: "nfl", espnId: "16" },
  { name: "New England Patriots", leagueLabel: "NFL", sport: "football", league: "nfl", espnId: "17" },
  { name: "New Orleans Saints",   leagueLabel: "NFL", sport: "football", league: "nfl", espnId: "18" },
  { name: "New York Giants",      leagueLabel: "NFL", sport: "football", league: "nfl", espnId: "19" },
  { name: "New York Jets",        leagueLabel: "NFL", sport: "football", league: "nfl", espnId: "20" },
  { name: "Philadelphia Eagles",  leagueLabel: "NFL", sport: "football", league: "nfl", espnId: "21" },
  { name: "Pittsburgh Steelers",  leagueLabel: "NFL", sport: "football", league: "nfl", espnId: "23" },
  { name: "San Francisco 49ers",  leagueLabel: "NFL", sport: "football", league: "nfl", espnId: "25" },
  { name: "Seattle Seahawks",     leagueLabel: "NFL", sport: "football", league: "nfl", espnId: "26" },
  { name: "Tampa Bay Buccaneers", leagueLabel: "NFL", sport: "football", league: "nfl", espnId: "27" },
  { name: "Tennessee Titans",     leagueLabel: "NFL", sport: "football", league: "nfl", espnId: "10" },
  { name: "Washington Commanders",leagueLabel: "NFL", sport: "football", league: "nfl", espnId: "28" },

  // ── NBA ────────────────────────────────────────────────────────────────────
  { name: "Atlanta Hawks",           leagueLabel: "NBA", sport: "basketball", league: "nba", espnId: "1"  },
  { name: "Boston Celtics",          leagueLabel: "NBA", sport: "basketball", league: "nba", espnId: "2"  },
  { name: "Brooklyn Nets",           leagueLabel: "NBA", sport: "basketball", league: "nba", espnId: "17" },
  { name: "Charlotte Hornets",       leagueLabel: "NBA", sport: "basketball", league: "nba", espnId: "30" },
  { name: "Chicago Bulls",           leagueLabel: "NBA", sport: "basketball", league: "nba", espnId: "4"  },
  { name: "Cleveland Cavaliers",     leagueLabel: "NBA", sport: "basketball", league: "nba", espnId: "5"  },
  { name: "Dallas Mavericks",        leagueLabel: "NBA", sport: "basketball", league: "nba", espnId: "6"  },
  { name: "Denver Nuggets",          leagueLabel: "NBA", sport: "basketball", league: "nba", espnId: "7"  },
  { name: "Detroit Pistons",         leagueLabel: "NBA", sport: "basketball", league: "nba", espnId: "8"  },
  { name: "Golden State Warriors",   leagueLabel: "NBA", sport: "basketball", league: "nba", espnId: "9"  },
  { name: "Houston Rockets",         leagueLabel: "NBA", sport: "basketball", league: "nba", espnId: "10" },
  { name: "Indiana Pacers",          leagueLabel: "NBA", sport: "basketball", league: "nba", espnId: "11" },
  { name: "LA Clippers",             leagueLabel: "NBA", sport: "basketball", league: "nba", espnId: "12", aliases: ["Los Angeles Clippers", "Clippers"] },
  { name: "Los Angeles Lakers",      leagueLabel: "NBA", sport: "basketball", league: "nba", espnId: "13" },
  { name: "Memphis Grizzlies",       leagueLabel: "NBA", sport: "basketball", league: "nba", espnId: "29" },
  { name: "Miami Heat",              leagueLabel: "NBA", sport: "basketball", league: "nba", espnId: "14" },
  { name: "Milwaukee Bucks",         leagueLabel: "NBA", sport: "basketball", league: "nba", espnId: "15" },
  { name: "Minnesota Timberwolves",  leagueLabel: "NBA", sport: "basketball", league: "nba", espnId: "16" },
  { name: "New Orleans Pelicans",    leagueLabel: "NBA", sport: "basketball", league: "nba", espnId: "3"  },
  { name: "New York Knicks",         leagueLabel: "NBA", sport: "basketball", league: "nba", espnId: "18" },
  { name: "Oklahoma City Thunder",   leagueLabel: "NBA", sport: "basketball", league: "nba", espnId: "25" },
  { name: "Orlando Magic",           leagueLabel: "NBA", sport: "basketball", league: "nba", espnId: "19" },
  { name: "Philadelphia 76ers",      leagueLabel: "NBA", sport: "basketball", league: "nba", espnId: "20", aliases: ["Sixers", "76ers"] },
  { name: "Phoenix Suns",            leagueLabel: "NBA", sport: "basketball", league: "nba", espnId: "21" },
  { name: "Portland Trail Blazers",  leagueLabel: "NBA", sport: "basketball", league: "nba", espnId: "22", aliases: ["Blazers"] },
  { name: "Sacramento Kings",        leagueLabel: "NBA", sport: "basketball", league: "nba", espnId: "23" },
  { name: "San Antonio Spurs",       leagueLabel: "NBA", sport: "basketball", league: "nba", espnId: "24" },
  { name: "Toronto Raptors",         leagueLabel: "NBA", sport: "basketball", league: "nba", espnId: "28" },
  { name: "Utah Jazz",               leagueLabel: "NBA", sport: "basketball", league: "nba", espnId: "26" },
  { name: "Washington Wizards",      leagueLabel: "NBA", sport: "basketball", league: "nba", espnId: "27" },

  // ── MLB ────────────────────────────────────────────────────────────────────
  { name: "Arizona Diamondbacks", leagueLabel: "MLB", sport: "baseball", league: "mlb", espnId: "29", aliases: ["D-backs"] },
  { name: "Athletics",            leagueLabel: "MLB", sport: "baseball", league: "mlb", espnId: "11", aliases: ["Oakland Athletics", "Oakland A's", "A's"] },
  { name: "Atlanta Braves",       leagueLabel: "MLB", sport: "baseball", league: "mlb", espnId: "15" },
  { name: "Baltimore Orioles",    leagueLabel: "MLB", sport: "baseball", league: "mlb", espnId: "1"  },
  { name: "Boston Red Sox",       leagueLabel: "MLB", sport: "baseball", league: "mlb", espnId: "2"  },
  { name: "Chicago Cubs",         leagueLabel: "MLB", sport: "baseball", league: "mlb", espnId: "16" },
  { name: "Chicago White Sox",    leagueLabel: "MLB", sport: "baseball", league: "mlb", espnId: "4"  },
  { name: "Cincinnati Reds",      leagueLabel: "MLB", sport: "baseball", league: "mlb", espnId: "17" },
  { name: "Cleveland Guardians",  leagueLabel: "MLB", sport: "baseball", league: "mlb", espnId: "5"  },
  { name: "Colorado Rockies",     leagueLabel: "MLB", sport: "baseball", league: "mlb", espnId: "27" },
  { name: "Detroit Tigers",       leagueLabel: "MLB", sport: "baseball", league: "mlb", espnId: "6"  },
  { name: "Houston Astros",       leagueLabel: "MLB", sport: "baseball", league: "mlb", espnId: "18" },
  { name: "Kansas City Royals",   leagueLabel: "MLB", sport: "baseball", league: "mlb", espnId: "7"  },
  { name: "Los Angeles Angels",   leagueLabel: "MLB", sport: "baseball", league: "mlb", espnId: "3"  },
  { name: "Los Angeles Dodgers",  leagueLabel: "MLB", sport: "baseball", league: "mlb", espnId: "19" },
  { name: "Miami Marlins",        leagueLabel: "MLB", sport: "baseball", league: "mlb", espnId: "28" },
  { name: "Milwaukee Brewers",    leagueLabel: "MLB", sport: "baseball", league: "mlb", espnId: "8"  },
  { name: "Minnesota Twins",      leagueLabel: "MLB", sport: "baseball", league: "mlb", espnId: "9"  },
  { name: "New York Mets",        leagueLabel: "MLB", sport: "baseball", league: "mlb", espnId: "21" },
  { name: "New York Yankees",     leagueLabel: "MLB", sport: "baseball", league: "mlb", espnId: "10" },
  { name: "Philadelphia Phillies",leagueLabel: "MLB", sport: "baseball", league: "mlb", espnId: "22" },
  { name: "Pittsburgh Pirates",   leagueLabel: "MLB", sport: "baseball", league: "mlb", espnId: "23" },
  { name: "San Diego Padres",     leagueLabel: "MLB", sport: "baseball", league: "mlb", espnId: "25" },
  { name: "San Francisco Giants", leagueLabel: "MLB", sport: "baseball", league: "mlb", espnId: "26" },
  { name: "Seattle Mariners",     leagueLabel: "MLB", sport: "baseball", league: "mlb", espnId: "12" },
  { name: "St. Louis Cardinals",  leagueLabel: "MLB", sport: "baseball", league: "mlb", espnId: "24" },
  { name: "Tampa Bay Rays",       leagueLabel: "MLB", sport: "baseball", league: "mlb", espnId: "30" },
  { name: "Texas Rangers",        leagueLabel: "MLB", sport: "baseball", league: "mlb", espnId: "13" },
  { name: "Toronto Blue Jays",    leagueLabel: "MLB", sport: "baseball", league: "mlb", espnId: "14" },
  { name: "Washington Nationals", leagueLabel: "MLB", sport: "baseball", league: "mlb", espnId: "20" },

  // ── NHL ────────────────────────────────────────────────────────────────────
  { name: "Anaheim Ducks",        leagueLabel: "NHL", sport: "hockey", league: "nhl", espnId: "25" },
  { name: "Boston Bruins",        leagueLabel: "NHL", sport: "hockey", league: "nhl", espnId: "1"  },
  { name: "Buffalo Sabres",       leagueLabel: "NHL", sport: "hockey", league: "nhl", espnId: "2"  },
  { name: "Calgary Flames",       leagueLabel: "NHL", sport: "hockey", league: "nhl", espnId: "3"  },
  { name: "Carolina Hurricanes",  leagueLabel: "NHL", sport: "hockey", league: "nhl", espnId: "7"  },
  { name: "Chicago Blackhawks",   leagueLabel: "NHL", sport: "hockey", league: "nhl", espnId: "4"  },
  { name: "Colorado Avalanche",   leagueLabel: "NHL", sport: "hockey", league: "nhl", espnId: "17" },
  { name: "Columbus Blue Jackets",leagueLabel: "NHL", sport: "hockey", league: "nhl", espnId: "29" },
  { name: "Dallas Stars",         leagueLabel: "NHL", sport: "hockey", league: "nhl", espnId: "9"  },
  { name: "Detroit Red Wings",    leagueLabel: "NHL", sport: "hockey", league: "nhl", espnId: "5"  },
  { name: "Edmonton Oilers",      leagueLabel: "NHL", sport: "hockey", league: "nhl", espnId: "6"  },
  { name: "Florida Panthers",     leagueLabel: "NHL", sport: "hockey", league: "nhl", espnId: "26" },
  { name: "Los Angeles Kings",    leagueLabel: "NHL", sport: "hockey", league: "nhl", espnId: "8"  },
  { name: "Minnesota Wild",       leagueLabel: "NHL", sport: "hockey", league: "nhl", espnId: "30" },
  { name: "Montreal Canadiens",   leagueLabel: "NHL", sport: "hockey", league: "nhl", espnId: "10" },
  { name: "Nashville Predators",  leagueLabel: "NHL", sport: "hockey", league: "nhl", espnId: "27" },
  { name: "New Jersey Devils",    leagueLabel: "NHL", sport: "hockey", league: "nhl", espnId: "11" },
  { name: "New York Islanders",   leagueLabel: "NHL", sport: "hockey", league: "nhl", espnId: "12" },
  { name: "New York Rangers",     leagueLabel: "NHL", sport: "hockey", league: "nhl", espnId: "13" },
  { name: "Ottawa Senators",      leagueLabel: "NHL", sport: "hockey", league: "nhl", espnId: "14" },
  { name: "Philadelphia Flyers",  leagueLabel: "NHL", sport: "hockey", league: "nhl", espnId: "15" },
  { name: "Pittsburgh Penguins",  leagueLabel: "NHL", sport: "hockey", league: "nhl", espnId: "16" },
  { name: "San Jose Sharks",      leagueLabel: "NHL", sport: "hockey", league: "nhl", espnId: "18" },
  { name: "Seattle Kraken",       leagueLabel: "NHL", sport: "hockey", league: "nhl", espnId: "124292" },
  { name: "St. Louis Blues",      leagueLabel: "NHL", sport: "hockey", league: "nhl", espnId: "19" },
  { name: "Tampa Bay Lightning",  leagueLabel: "NHL", sport: "hockey", league: "nhl", espnId: "20" },
  { name: "Toronto Maple Leafs",  leagueLabel: "NHL", sport: "hockey", league: "nhl", espnId: "21" },
  { name: "Utah Mammoth",         leagueLabel: "NHL", sport: "hockey", league: "nhl", espnId: "129764", aliases: ["Arizona Coyotes", "Coyotes"] },
  { name: "Vancouver Canucks",    leagueLabel: "NHL", sport: "hockey", league: "nhl", espnId: "22" },
  { name: "Vegas Golden Knights", leagueLabel: "NHL", sport: "hockey", league: "nhl", espnId: "37"  },
  { name: "Washington Capitals",  leagueLabel: "NHL", sport: "hockey", league: "nhl", espnId: "23" },
  { name: "Winnipeg Jets",        leagueLabel: "NHL", sport: "hockey", league: "nhl", espnId: "28" },

  // ── Premier League ─────────────────────────────────────────────────────────
  { name: "AFC Bournemouth",           leagueLabel: "Premier League", sport: "soccer", league: "eng.1", espnId: "349" },
  { name: "Arsenal",                   leagueLabel: "Premier League", sport: "soccer", league: "eng.1", espnId: "359" },
  { name: "Aston Villa",               leagueLabel: "Premier League", sport: "soccer", league: "eng.1", espnId: "362" },
  { name: "Brentford",                 leagueLabel: "Premier League", sport: "soccer", league: "eng.1", espnId: "337" },
  { name: "Brighton & Hove Albion",    leagueLabel: "Premier League", sport: "soccer", league: "eng.1", espnId: "331", aliases: ["Brighton"] },
  { name: "Burnley",                   leagueLabel: "Premier League", sport: "soccer", league: "eng.1", espnId: "379" },
  { name: "Chelsea",                   leagueLabel: "Premier League", sport: "soccer", league: "eng.1", espnId: "363" },
  { name: "Crystal Palace",            leagueLabel: "Premier League", sport: "soccer", league: "eng.1", espnId: "384" },
  { name: "Everton",                   leagueLabel: "Premier League", sport: "soccer", league: "eng.1", espnId: "368" },
  { name: "Fulham",                    leagueLabel: "Premier League", sport: "soccer", league: "eng.1", espnId: "370" },
  { name: "Leeds United",              leagueLabel: "Premier League", sport: "soccer", league: "eng.1", espnId: "357" },
  { name: "Liverpool",                 leagueLabel: "Premier League", sport: "soccer", league: "eng.1", espnId: "364" },
  { name: "Manchester City",           leagueLabel: "Premier League", sport: "soccer", league: "eng.1", espnId: "382", aliases: ["Man City"] },
  { name: "Manchester United",         leagueLabel: "Premier League", sport: "soccer", league: "eng.1", espnId: "360", aliases: ["Man United", "Man Utd"] },
  { name: "Newcastle United",          leagueLabel: "Premier League", sport: "soccer", league: "eng.1", espnId: "361", aliases: ["Newcastle"] },
  { name: "Nottingham Forest",         leagueLabel: "Premier League", sport: "soccer", league: "eng.1", espnId: "393", aliases: ["Forest"] },
  { name: "Sunderland",                leagueLabel: "Premier League", sport: "soccer", league: "eng.1", espnId: "366" },
  { name: "Tottenham Hotspur",         leagueLabel: "Premier League", sport: "soccer", league: "eng.1", espnId: "367", aliases: ["Spurs", "Tottenham"] },
  { name: "West Ham United",           leagueLabel: "Premier League", sport: "soccer", league: "eng.1", espnId: "371", aliases: ["West Ham"] },
  { name: "Wolverhampton Wanderers",   leagueLabel: "Premier League", sport: "soccer", league: "eng.1", espnId: "380", aliases: ["Wolves"] },
];

export function searchTeams(query: string): EspnTeam[] {
  const q = query.toLowerCase().trim();
  if (!q) return [];
  return ESPN_TEAMS.filter(
    (t) =>
      t.name.toLowerCase().includes(q) ||
      t.aliases?.some((a) => a.toLowerCase().includes(q))
  ).slice(0, 5);
}
